### PR TITLE
Update stimulus-rails-nested-form.md

### PR DESCRIPTION
**Pull request by julienanne**
Fix the missing part to edit nested attributes by id.

The example is for an edit of user with nested attributes for todos, so we need to add the hidden field id for existant todo to avoid multiple creation instead of update ;)

Sorry if I have not following the process right ;)

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Hum, I'm not sure why you would need the hidden field here? The id of a persisted object if already in the name so Rails knows if it needs to create or update the object

Screenshot 2024-06-24 at 11 05 24

**Comment by julienanne** [comment]
Hum sorry I guess I have a edge case (I will verify it later) because from https://guides.rubyonrails.org/form_helpers.html#nested-forms  : "If the associated object is already saved, fields_for autogenerates a hidden input with the id of the saved record. You can disable this by passing include_id: false to fields_for."

So you should be right ;)

Have a nice day and thanks for the reply.

**Comment by julienanne** [comment]
I close the PR for the moment because I have no time to check it deeper and the docs lead to the point that this PR is wrong ;)

**Comment by julienanne** [comment]
Thanks for your reply! After checking my codebase, I realized the autogenerated ID wasn't where I expected it to be. Sorry for the confusion and any time lost. I really appreciate your work!

**Comment by guillaumebriday** [comment]
No worries, thanks for the contribution!

**Pull request closed without merging**
